"""
Pydantic models for RAG Agent API.
Defines request/response schemas with validation rules.
"""
from pydantic import BaseModel, Field, validator
from typing import List, Optional
from enum import Enum


class AgentRequest(BaseModel):
    """Request model for /ask endpoint."""

    query: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="User's natural language question"
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Number of document chunks to retrieve"
    )
    include_sources: bool = Field(
        default=True,
        description="Whether to include source attribution in response"
    )

    @validator("query")
    def query_not_empty(cls, v):
        """Validate query is not empty after trimming."""
        if not v.strip():
            raise ValueError("Query cannot be empty or whitespace only")
        return v.strip()


class SourceChunk(BaseModel):
    """Represents a retrieved document chunk with metadata."""

    content: str = Field(..., min_length=1, description="Text content of the retrieved chunk")
    url: str = Field(..., description="Source URL of the original document")
    chunk_id: str = Field(..., description="Identifier for the specific chunk")
    document_id: str = Field(..., description="Identifier for the parent document")
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Cosine similarity score")
    position: int = Field(..., ge=1, description="Rank in retrieval results (1-indexed)")


class ResponseMetadata(BaseModel):
    """Metadata about the response timing and performance."""

    response_time_ms: float = Field(ge=0, description="Total time taken to process the request in milliseconds")
    chunk_count: int = Field(ge=0, description="Number of retrieved chunks")
    embedding_time_ms: float = Field(ge=0, description="Time taken for embedding generation")
    retrieval_time_ms: float = Field(ge=0, description="Time taken for Qdrant retrieval")
    generation_time_ms: float = Field(ge=0, description="Time taken for OpenAI generation")


class AgentResponse(BaseModel):
    """Response model for /ask endpoint."""

    answer: str = Field(..., min_length=1, description="Natural language answer generated by the agent")
    sources: List[SourceChunk] = Field(description="List of retrieved document chunks used to generate the answer")
    metadata: ResponseMetadata = Field(description="Response timing and status information")


class ErrorType(str, Enum):
    """Error types for structured error responses."""
    VALIDATION_ERROR = "validation_error"
    AGENT_ERROR = "agent_error"
    SERVICE_UNAVAILABLE = "service_unavailable"
    TIMEOUT = "timeout"
    RATE_LIMITED = "rate_limited"
    UNKNOWN_ERROR = "unknown_error"


class ErrorResponse(BaseModel):
    """Error response model."""

    error: ErrorType = Field(..., description="Error type or category")
    message: str = Field(..., min_length=1, description="Human-readable error message")
    detail: Optional[str] = Field(None, description="Optional additional debugging information")
    status_code: int = Field(..., ge=400, le=599, description="HTTP status code")


class HealthResponse(BaseModel):
    """Health check response model."""

    status: str = Field(..., description="Overall health status")
    services: dict = Field(..., description="Status of external services")
    timestamp: str = Field(..., description="Timestamp of the health check")
